// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOViN4cTOVY2JfujPVoL0W68c3r2b1fck',
    appId: '1:235995319355:web:c6083b248376ab0155601e',
    messagingSenderId: '235995319355',
    projectId: 'nasrda-tracker',
    authDomain: 'nasrda-tracker.firebaseapp.com',
    storageBucket: 'nasrda-tracker.appspot.com',
    measurementId: 'G-ZRHBQWV40W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI8VPZKWj7kEgiCvv_OOm4WpgiGf2w2k4',
    appId: '1:235995319355:android:21327add5453d5b055601e',
    messagingSenderId: '235995319355',
    projectId: 'nasrda-tracker',
    storageBucket: 'nasrda-tracker.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2ToUQkhNORuX0_COiOY4FDKHTMKAu5cs',
    appId: '1:235995319355:ios:259bcb245c155af855601e',
    messagingSenderId: '235995319355',
    projectId: 'nasrda-tracker',
    storageBucket: 'nasrda-tracker.appspot.com',
    iosClientId: '235995319355-g3in9aack8s115hootmjjd1euohnabv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.tracker',
  );
}
